export const HARDWARE_AVAILABILITY_STATE = {
  UNKNOWN: 'UNKNOWN',
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;
export type HARDWARE_AVAILABILITY_STATE = typeof HARDWARE_AVAILABILITY_STATE;
export type A_HARDWARE_AVAILABILITY_STATE = HARDWARE_AVAILABILITY_STATE[keyof HARDWARE_AVAILABILITY_STATE];
