export const I2C_HARDWARE_STATE = {
  UNKNOWN: 'UNKNOWN',
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;
export type I2C_HARDWARE_STATE = typeof I2C_HARDWARE_STATE;
export type AN_I2C_HARDWARE_STATE = I2C_HARDWARE_STATE[keyof I2C_HARDWARE_STATE];
