export const INA219_BUS_VOLTAGE_RANGE = {
  RANGE_16V: 0,
  RANGE_32V: 1,
} as const;
export type INA219_BUS_VOLTAGE_RANGE = typeof INA219_BUS_VOLTAGE_RANGE;
export type AN_INA219_BUS_VOLTAGE_RANGE = INA219_BUS_VOLTAGE_RANGE[keyof INA219_BUS_VOLTAGE_RANGE];
