export declare const HARDWARE_AVAILABILITY_STATE: {
    readonly UNKNOWN: "UNKNOWN";
    readonly AVAILABLE: "AVAILABLE";
    readonly UNAVAILABLE: "UNAVAILABLE";
};
export declare type HARDWARE_AVAILABILITY_STATE = typeof HARDWARE_AVAILABILITY_STATE;
export declare type A_HARDWARE_AVAILABILITY_STATE = HARDWARE_AVAILABILITY_STATE[keyof HARDWARE_AVAILABILITY_STATE];
